### ISSUE TITLE
老哥你好，Demo 里面的链接失效了，能修复一下吗？

### ISSUE THREAD

**Issue by zhanglkx** [cat13954/IOSUiTableViewSample#1]

**Comment by cat13954** [comment]
地址已经修复了。

代码是很久之前的了，有点乱，第一次允许网络之后，首页刷新不出来，可以杀APP再启动就行了。

**Comment by zhanglkx** [comment]
> 地址已经修复了。
> 
> 代码是很久之前的了，有点乱，第一次允许网络之后，首页刷新不出来，可以杀APP再启动就行了。

非常感谢！很棒的demo，认真学习一下！
